# Generated by Django 6.0.2 on 2026-04-14 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, help_text='Texto del mensaje, máximo 1000 caracteres.', max_length=1000, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Evidencia fotográfica (PNG/JPG).', null=True, upload_to='chat_images/%Y/%m/')),
                ('estado', models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Visto', 'Visto')], default='Enviado', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
