# Generated by Django 6.0.2 on 2026-05-12 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Identificador externo')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('program_label', models.CharField(blank=True, max_length=200)),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('adherence_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='RehabWeb_API.patient')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='RehabWeb_API.session')),
            ],
            options={
                'verbose_name': 'Ejercicio de sesión',
                'verbose_name_plural': 'Ejercicios de sesión',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='RehabWeb_API.therapist'),
        ),
        migrations.CreateModel(
            name='InactivityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_since_last_session', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días desde última sesión')),
                ('last_session_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('no_sessions', 'Sin sesiones registradas')], default='low', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_alerts', to='RehabWeb_API.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_alerts', to='RehabWeb_API.therapist')),
            ],
            options={
                'verbose_name': 'Alerta de inactividad',
                'verbose_name_plural': 'Alertas de inactividad',
            },
        ),
        migrations.CreateModel(
            name='TherapistPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis', models.CharField(blank=True, max_length=500, verbose_name='Diagnóstico principal')),
                ('clinical_status', models.CharField(choices=[('riesgo', 'Riesgo'), ('activo', 'Activo'), ('alta', 'Alta')], default='activo', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_links', to='RehabWeb_API.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='RehabWeb_API.therapist')),
            ],
            options={
                'verbose_name': 'Vínculo terapeuta-paciente',
                'verbose_name_plural': 'Vínculos terapeuta-paciente',
            },
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('rom_week', 'ROM semanal'), ('temporal', 'Serie temporal')], max_length=32)),
                ('period_label', models.CharField(max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('meta_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('observed_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_points', to='RehabWeb_API.patient')),
            ],
            options={
                'verbose_name': 'Punto de métrica',
                'verbose_name_plural': 'Puntos de métrica',
                'ordering': ('metric_type', 'sort_order', 'period_label'),
                'indexes': [models.Index(fields=['patient', 'metric_type', 'sort_order'], name='RehabWeb_AP_patient_903f29_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['patient', 'occurred_at'], name='RehabWeb_AP_patient_cea73d_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['therapist', 'occurred_at'], name='RehabWeb_AP_therapi_3d73c2_idx'),
        ),
        migrations.AddIndex(
            model_name='inactivityalert',
            index=models.Index(fields=['therapist', 'updated_at'], name='RehabWeb_AP_therapi_29e62f_idx'),
        ),
        migrations.AddConstraint(
            model_name='inactivityalert',
            constraint=models.UniqueConstraint(fields=('therapist', 'patient'), name='uniq_inactivity_therapist_patient'),
        ),
        migrations.AddIndex(
            model_name='therapistpatient',
            index=models.Index(fields=['therapist', 'deleted_at'], name='RehabWeb_AP_therapi_992ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistpatient',
            index=models.Index(fields=['therapist', 'clinical_status'], name='RehabWeb_AP_therapi_fd17dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='therapistpatient',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('therapist', 'patient'), name='uniq_active_therapist_patient'),
        ),
    ]
